### PR TITLE
Added random codes for group id 0 (Lidl switches)

### PR DESCRIPTION
**Pull request by DionysiusLac**
I have some Lidl switches and got them working by adding the random codes to the protocol. As I am a developer but have not used GitHub before I wanted to push my changes myself. So this is my first pull request! Hope I followed the manual correctly and checked all the correct tickboxes :-)

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you find some forum users to test these changes?

**Comment by DionysiusLac** [comment]
I do not think there is anyone that can. One needs exactly to have a quigg based switch set, the switches need to be group 0 (out of 16 different groups) and is able to compile pilight. Chances are slim that I find someone that can. As 8 of the 16 groups are still undefined, this indicates there are not a lot of quigg users of the gt1000 set.

**Comment by DionysiusLac** [comment]
This the forum thread by the way, which I could ask for a tester, but the last serious post is of may 2014..
https://forum.pilight.org/Thread-Quigg-GT-1000?page=6&highlight=quigg

**Comment by CurlyMoo** [comment]
Just try and we'll see.

**Comment by DionysiusLac** [comment]
And now we wait :-)
https://forum.pilight.org/Thread-Quigg-GT-1000?pid=18963#pid18963

**Comment by DionysiusLac** [comment]
Hi CurlyMoo,

No response yet. As the changes are trivial, perhaps you could take a look and merge it for other (future) users with a group 0 switch set, as well for me so my set is natively supported in the next release?

Thanks!

**Comment by DionysiusLac** [comment]
*Bump*

**Comment by DionysiusLac** [comment]
Thanks!

**Pull request merged**
