### PR TITLE
add support for secudo / FlammEx smoke sensor protocol

### PR DESCRIPTION
**Pull request by cxxcoder**
This code adds support for the protocol used by secudo / FlammEx smoke sensors. (The manufacturer has just changed its name from FlammEx to secudo.)
The smoke sensors have 10 dip switches by which the id can be configured. There is only one signal type meaning alarm - no separate signals for alarm on and off.
Because there was no matching device type and I did not want to misuse an existing one like MOTION this code introduces a new device type ALARM.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
What a nice PR :+1:

**Comment by CurlyMoo** [comment]
Is it just me or was there never a wiki entry? I want to include this protocol in the new stable version, but i need a manual page (instead of the deprecated wiki) for it.

**Comment by cxxcoder** [comment]
Hello, I can create next week a manual page for it. Before I will
unfortunately have no time.

Am 03.10.2017 7:29 nachm. schrieb "CurlyMoo" <notifications@github.com>:

Is it just me or was there never a wiki entry? I want to include this
protocol in the new stable version, but i need a manual page (instead of
the deprecated wiki) for it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pilight/pilight/pull/239#issuecomment-333919158>, or mute
the thread

**Comment by CurlyMoo** [comment]
Can i expect the documentation before or in this weekend? This PR is a good reference:
https://github.com/pilight/pilight/pull/389

**Comment by cxxcoder** [comment]
Yes, I will create one before the weekend. At the latest I will have time
on Friday in any case for doing it.

2017-10-10 22:27 GMT+02:00 CurlyMoo <notifications@github.com>:

**Pull request merged**
