### PR TITLE
add further GT-9000 support

### PR DESCRIPTION
**Pull request by dominikkarall**
Hi,

this PR adds further GT-9000 protocol support - more systemcodes are supported now.

Regards,
Dominik

### CODE REVIEW

**Comment by CurlyMoo** [comment]
You forgot the version number increase.

But most important, don't close this PR.

**Comment by dominikkarall** [comment]
Updated version number.

**Comment by CurlyMoo** [comment]
Is it just me or was there never a wiki entry? I want to include this protocol in the new stable version, but i need a manual page (instead of the deprecated wiki) for it.

**Comment by CurlyMoo** [comment]
@dominikkarall Any news on this?

**Comment by dominikkarall** [comment]
I can provide it within the next 2 weeks. Hope that's ok.

**Comment by CurlyMoo** [comment]
The release of the new pilight version is depending on it, so it's rather a question if the users can wait or if you'll be linched in the meantime 😉

**Comment by dominikkarall** [comment]
@CurlyMoo can you please provide me a link to a wiki page where I can put the information on? It seems that I don't have the permission to create a new wiki page.

**Comment by CurlyMoo** [comment]
You can find a similar pull here:
https://github.com/pilight/pilight/pull/389

**Pull request merged**
