### PR TITLE
Update arctech_switch.c to be compatible with smartwares switches

### PR DESCRIPTION
**Pull request by sreinelt**
As discussed here:
https://forum.pilight.org/Thread-Smartwares-SHS-53000-radiator-valve?pid=21766#pid21766
Change pulse length for second start pulse from 9* to 8*

### CODE REVIEW

**Comment by pilino1234** [comment]
Can you add that forum link to the actual commit description please? Looks good otherwise, although it would be good to get other users to confirm that their devices still work / work better after this change.

**Comment by CurlyMoo** [comment]
Mine do.

**Comment by sreinelt** [comment]
Github doesn't allow me to change the commit description as the commit has already been pulled to my main repository.

**Comment by pilino1234** [comment]
Just use the git cli: `git commit --amend` and edit the commit description. Then force push to your branch on your fork to update the PR

**Comment by pilino1234** [comment]
Commit description looks good now, but you used a different email when amending the commit. Make sure that your `git config` for your local clone contains the same email as your @sreinelt GitHub account

**Comment by sreinelt** [comment]
Should be all as requested now. Did I mention that I hate git? ;-)

**Comment by CurlyMoo** [comment]
It would like to change the commit to;
```
Make arctech switch compatible with smartware valves

The start pulse was made shorter from 9 to 8 times PULSE_DIV

Corresponding discussion:
https://forum.pilight.org/Thread-Smartwares-SHS-53000-radiator-valve?page=3
```

**Comment by sreinelt** [comment]
It's not just about valves - they are nothing but switches. I've tested it with two different switch types but with no valve.

**Comment by CurlyMoo** [comment]
Can you open a PR on rewrite as well with a unit test included?

**Comment by sreinelt** [comment]
Is there any guide regarding the unit test for a protocol?

**Comment by CurlyMoo** [comment]
Not yet, but you are capable enough to understand i think.

https://github.com/pilight/pilight/tree/rewrite/tests/protocols
https://github.com/pilight/pilight/blob/rewrite/tests/protocols_433.c
https://github.com/pilight/pilight/blob/rewrite/tests/protocols/arctech_dimmer.h

Howto compile and run
https://github.com/pilight/pilight/blob/rewrite/ci/travis-script.sh

If you just want to run the protocol test, disable the rest here:
https://github.com/pilight/pilight/blob/rewrite/tests/alltests.c

**Pull request closed without merging**
