### PR TITLE
Updated jquery and moment frameworks and renamed filenames

### PR DESCRIPTION
**Pull request by TopdRob**
Updated frameworks to the newest versions and removed the versions from
the filenames

### CODE REVIEW

**Comment by CurlyMoo** [comment]
What versions are they?

**Comment by TopdRob** [comment]
jquery - version 3.1.1
moment.js - version 2.17.1
jquery mobile untouched

**Comment by CurlyMoo** [comment]
Have you tested everything?

**Comment by TopdRob** [comment]
Yes, works perfect on my local raspberry pi. 
image

Updated the files in /usr/local/share/pilight

**Comment by CurlyMoo** [comment]
Did you also try all elements like screens, datetime, etc that pilight supports?

**Comment by TopdRob** [comment]
I've tested with my default configuration containing switches, dimmers, datetime, label and weather. I added in my test configuration the screen and webcam elements and they work fine as well.
image

**Comment by CurlyMoo** [comment]
@pilino1234 and @wo-rasp , did you test it as well?

**Comment by wo-rasp** [comment]
I have integrated PR 317 it into my test_dev branch and so far I have not found issues with somfy (UP/STOP/DOWN), philipshue (dimlevel), tfa, switches and screen protocols.
I am using firefox (50.0.2) and have not performed any tests with IE, Edge, Chrome, Safari, Opera.

**Comment by wo-rasp** [comment]
As far as i see it there were no issues related to the upgrade.

**Comment by CurlyMoo** [comment]
As soon as this is squashed into one commit, i can merge.

**Comment by wo-rasp** [comment]
Oops, commit 83f7c9d has changes for multiple protocols and main modules.
I think they have to be removed from the pull request upfront.

**Comment by wo-rasp** [comment]
TopdRob, can you combine
| * | d9480ed Added jquery-migrate to support jquery v3 >
| * | a2797c4 Updated jquery and moment frameworks and renamed filenames
into one commit ?
I do not tink that is advisable to include commit 83f7c9d as discussed above.

**Comment by TopdRob** [comment]
Hi wo-rasp,
I already deleted the fork and now I don't know how I could rebase this pull request.

**Comment by pilino1234** [comment]
You will need to open a new PR, since GitHub afaik doesn't allow you to mess with the source fork/branch. Just make a fresh clone of the latest development branch and apply your changes on top of that, or rebase your branch (if you still have it locally).

**Comment by wo-rasp** [comment]
If you have not deleted your local repository do the following:

git reflog
You will see something similar like this:
83f7c9d HEAD@{15}: ........

git reset --hard HEAD@{15}
git log --oneline --graph --decorate -n 3
You should see the 3 commits of your branch you based your pull request on:
* 83f7c9d
* d9480ed
* a2797c4

git rebase -i HEAD~3
Your standard editor will open, delete the line that says:
pick 83f7c9d

Save the file.
Push the local branch to your github repository.
If everything was done properly github will update the pull request automatically.

**Comment by pilino1234** [comment]
>github will update your original pull request automatically.

Nope, sadly github won't restore pull requests if the fork was deleted (just tested it myself). If only the branch was deleted, the PR will be closed automatically, but if the fork was deleted only the source branch will be labelled as `unkown repository` (which is the case here). In this case, there is no way out but to open a new PR.

**Comment by wo-rasp** [comment]
Thanks, i noticed the unknown repository reference, and was wondering mysolf a bit why and how that happened.

**Comment by pilino1234** [comment]
This can be closed, replaced by #336

**Pull request closed without merging**
