### PR TITLE
Update jquery and moment librairies in webgui

### PR DESCRIPTION
**Pull request by TopdRob**
Update and rename jquery.mobile-1.4.2.min.css to jquery.mobile-1.4.5.min.css

Update and rename jquery.mobile-1.4.2.min.js to jquery.mobile-1.4.5.min.js

Update moment.js to v2.10.6

Update index.html version numbers jquery

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Why was the previous PR closed as i explicitly asked not to do?

**Comment by TopdRob** [comment]
I deleted my fork to start over

**Comment by CurlyMoo** [comment]
Can you undelete it?

**Comment by TopdRob** [comment]
why?

**Comment by CurlyMoo** [comment]
Because as i also explicitly mention in the contribution guide:

> [...] be aware that contributing to a big project shouldn't be considered a playground. It also isn't meant for you to learn git. So if you don't know what you are doing than don't do it. Instead open an forum topic, point to your code, and ask for help.

I could have fixed the PR from my side when absolutely necessary.

**Comment by TopdRob** [comment]
I'm sorry but the repo used for pull request 192 can't be restored anymore

**Comment by CurlyMoo** [comment]
Can i trust you to not open and close PR's without consulting me first?

**Comment by TopdRob** [comment]
I will do in future. Sorry again

**Pull request merged**
