### PR TITLE
Elro fa20rf

### PR DESCRIPTION
**Pull request by mel0en**
Update to pilight v 02-03-2015

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you redo the branch + PR so all is in one commit?

**Comment by CurlyMoo** [comment]
Also add the windows checks in the defines.

**Comment by mel0en** [comment]
Sorry for the confusion, made a mistake with the elro_fa20rf protocol.

**Comment by mel0en** [comment]
Could you elaborate on the windows checks in the defines a bit? I cannot find any windows checks in other protocols?

**Comment by CurlyMoo** [comment]
https://github.com/pilight/pilight/blob/development/libs/protocols/alecto_ws1700.c#L143
https://github.com/pilight/pilight/blob/development/libs/protocols/alecto_ws1700.c#L176

**Comment by mel0en** [comment]
Clear, thanks!

**Pull request closed without merging**
