### PR TITLE
Action switch support

### PR DESCRIPTION
**Pull request by puuu**

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Is action the same as impuls?

**Comment by puuu** [comment]
Hmm, it looks like this. I did not realized before. Indeed, the switch works with impuls, but not the transmitter. 

The average timing from the transmitter is:
short: 190 (175-201)
long: 553 (544-560)
footer: 5798 (5518-5854)

So, we need at least MIN_PULSE_LENGTH=160 in impuls to work. If you think it is better to change impuls please do, or let me know to, if I should make a new pull request.

**Comment by CurlyMoo** [comment]
Impuls was one of the first protocol supported and the last years we haven't had complains of it not working.

**Comment by puuu** [comment]
Ok, but increasing `MIN_PULSE_LENGTH` from 130 to 160 will not break anything? And at least, my remote is working...

**Comment by CurlyMoo** [comment]
So discuss it on the forum and hear if others can confirm.

**Pull request closed without merging**
