### PR TITLE
Quigg gt7000 sw

### PR DESCRIPTION
**Pull request by wo-rasp**
@curlymo,
Sorry was not meant against master. Please close the request.  
The GT7000 remote control starts with id=13 and when the button "neuer code" is pressed the id is incremented by 1 until the id rolls over at 4095.

The current driver handles the binary id in reverse order, thus the id starts with 2816, 1792, 3840, 128, 2176 ...

### CODE REVIEW

**Comment by CurlyMoo** [comment]
You can edit your pull request to target the right branch.

**Comment by wo-rasp** [comment]
I tried, git won’t allow me to edit – pls refuse & close pull request

 

Von: CurlyMoo [mailto:notifications@github.com] 
Gesendet: Samstag, 31. Januar 2015 01:08
An: pilight/pilight
Cc: wo-rasp
Betreff: Re: [pilight] Quigg gt7000 sw (#137)

 

You can edit your pull request to target the right branch.

**Comment by CurlyMoo** [comment]
Just to be sure. Please create a pull request per change (from separate branches). So don't include 'arctech_switch` stuff in a quigg pull request.

**Comment by wo-rasp** [comment]
Yes it is my intention to do so. Will re-check to ensure.

 

 

Von: CurlyMoo [mailto:notifications@github.com] 
Gesendet: Samstag, 31. Januar 2015 10:34
An: pilight/pilight
Cc: wo-rasp
Betreff: Re: [pilight] Quigg gt7000 sw (#137)

 

Just to be sure. Please create a pull request per change (from separate branches). So don't include 'arctech_switch` stuff in a quigg pull request.

**Pull request closed without merging**
