### PR TITLE
add bme280 to Rewrite

### PR DESCRIPTION
**Pull request by magallant**

### CODE REVIEW

**Comment by magallant** [comment]
`/root/rewrite/pilight-1/libs/pilight/protocols/GPIO/bme280.c:33:32: fatal error: ../../core/threads.h: No such file or directory
 #include "../../core/threads.h"
`
Why is there no threads.h in the core directory in the rewrite branch ?

**Comment by magallant** [comment]
and no gc.h neither in the core directory ?

**Comment by CurlyMoo** [comment]
Because that codebase has been massively rewriten, hence the `rewrite` branch :wink:

Is the codebase for the `BMP180` of any use?

**Comment by magallant** [comment]
I see ... 
I will have to do some (code-)reading... Indeed, the bmp180 codebase is the guide...

**Comment by magallant** [comment]
I got the 'rewrite' code to compile, But the daemon fails to start :
`root@Zero:~/rewrite/pilight-1# pilight-daemon -D
pilight-daemon: symbol lookup error: pilight-daemon: undefined symbol: config_set_file`

I cannot find much info on this error ... Any hints ?
Matthias

**Comment by CurlyMoo** [comment]
The rewrite branch shouldn't be able to compile the daemon, so that's wierd. You should only be able to run the unittests. Building is done like in this file: https://github.com/pilight/pilight/blob/rewrite/ci/travis-script.sh

To run a specific unittest do:
```
# ./pilight-unittest test_common
``` 

To get a list of all unittests:
```
# ./pilight-unittest list
```

**Comment by magallant** [comment]
building with (the commands of) the script fails :
`[ 98%] Building C object CMakeFiles/pilight-unittest.dir/tests/webserver_rest.c.o
[ 98%] Linking C executable pilight-unittest
CMakeFiles/pilight-unittest.dir/tests/alltests.c.o: In function `RunAllTests':
/root/rewrite/pilight-1/tests/alltests.c:162: undefined reference to `plua_coverage_output'
/root/rewrite/pilight-1/tests/alltests.c:290: undefined reference to `plua_flush_coverage'
CMakeFiles/pilight-unittest.dir/tests/lua_async_event.c.o: In function `test_lua_async_event_missing_parameters':
/root/rewrite/pilight-1/tests/lua_async_event.c:216: undefined reference to `plua_pause_coverage'
/root/rewrite/pilight-1/tests/lua_async_event.c:241: undefined reference to `plua_pause_coverage'
CMakeFiles/pilight-unittest.dir/tests/lua_async_event.c.o: In function `test_lua_async_event':
/root/rewrite/pilight-1/tests/lua_async_event.c:284: undefined reference to `plua_pause_coverage'
/root/rewrite/pilight-1/tests/lua_async_event.c:344: undefined reference to `plua_pause_coverage'
CMakeFiles/pilight-unittest.dir/tests/lua_async_thread.c.o: In function `test_lua_async_thread_missing_parameters':
/root/rewrite/pilight-1/tests/lua_async_thread.c:170: undefined reference to `plua_pause_coverage'
CMakeFiles/pilight-unittest.dir/tests/lua_async_thread.c.o:/root/rewrite/pilight-1/tests/lua_async_thread.c:192: more undefined references to `plua_pause_coverage' follow
collect2: error: ld returned 1 exit status
CMakeFiles/pilight-unittest.dir/build.make:2375: recipe for target 'pilight-unittest' failed
make[2]: *** [pilight-unittest] Error 1
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/pilight-unittest.dir/all' failed
make[1]: *** [CMakeFiles/pilight-unittest.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by CurlyMoo** [comment]
Did you start with a clen build dir?

**Comment by magallant** [comment]
Yes indeed, an unclean build dir was the problem....
I added the BME280 to the test code, it compiles, but ...
I do not have the I2C-stub driver/kernel-module on my Pi Zero.
Do you have any hints on how I can install it ? I can't find anything usefull on this... 

cheers,
Matthias

**Comment by CurlyMoo** [comment]
Does this work:
https://felipeogutierrez.blogspot.com/2018/11/creating-virtual-ic-kernel-module-for.html

**Comment by magallant** [comment]
No output for 10 minutes ... Is that something I can fix ?

**Comment by CurlyMoo** [comment]
> No output for 10 minutes ... Is that something I can fix ?

By restarting the test :smile:

**Comment by CurlyMoo** [comment]
PR was manually merged. Thanks.

**Pull request closed without merging**
