### PR TITLE
[Docs] Missing package on installation manual

### PR DESCRIPTION
**Pull request by Tamadite**
Under the "Installation" chapter, under "Manually Compiled Version", point #4 package luajit-5.1 is missing in the list. The error the user would get is:

`
CMake Error at CMakeLists.txt:303 (message):
 Looking for libluajit - not found
-- Configuring incomplete, errors occurred!
See also "/home/pi/pilight/pilight/build/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'install'.  Stop.`
package

### CODE REVIEW

**Comment by CurlyMoo** [comment]
You can always fix a PR. No need to close it. We can help you with it.

**Comment by Tamadite** [comment]
This PR is to merge 92 commits into staging from development which was not my intention therefore I close it.

**Comment by Tamadite** [comment]
This PR is to merge 92 commits into staging from development which was not my intention therefore I close it.

**Comment by CurlyMoo** [comment]
That why we are going to fix this one. PRs can always be fixed.

**Comment by CurlyMoo** [comment]
You can do the following:

First fork the repository

```
git clone -b staging https://github.com/pilight/pilight.git
git remote rm origin
git remote add origin https://github.com/Tamadite/pilight.git
```

Then make do you additions in the docs and commit.
```
git push -f origin staging
```
Then get back to me. If one of the commands failed, tell me as well.

**Comment by Tamadite** [comment]
Changes on installation.rst done!

`git push -f origin staging`

executed resulting on 

`Everything up-to-date`

**Comment by CurlyMoo** [comment]
Did you actually commit your changes before pushing?

**Comment by Tamadite** [comment]
my bad... fixed now!  
commit:
`staging ed2a211e`

push:
`To https://github.com/Tamadite/pilight.git
   44c16d6d..ed2a211e  staging -> staging`

**Pull request closed without merging**
