### PR TITLE
implement media access control by csma and csma/cd

### PR DESCRIPTION
**Pull request by andiwand**

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you adapt the module to the rewrite code?

**Comment by andiwand** [comment]
yes, i will create a new request later.

**Comment by CurlyMoo** [comment]
Never close PR's, but resolve them. Forgot to mention that.

**Comment by andiwand** [comment]
i hope you can help me with the rewrite... i managed to merge all files, except daemon.c.
some things i cannot find:
- recvqueue_t
- receive_queue
- receiveOOK

**Comment by CurlyMoo** [comment]
There are no more queue's, just tasks in worker queues.

**Comment by andiwand** [comment]
i see. it will take some time to implement this with the new base. i will tell you when i got it.

**Comment by andiwand** [comment]
my modules works so far. i added a send queue to 433gpio which will only be active if you use csma or csma/cd.
still there is the problem that i cannot set options to be optional (https://github.com/andiwand/pilight/blob/feature/csmacd/libs/pilight/hardware/433gpio.c#L609). e.g. someone should not be forced to add "csma-wait-n-frames" to his config, because there is a default value.

i discovered a bug in the daemon. the first send operation (i triggered it by the webinterface) causes 100% load. after the second one it dropps back to normal. i would fix it as well, but thought you might be way faster, since i do not know the daemon well.

i will squash the temporary commits later!

**Comment by CurlyMoo** [comment]
Can you (without closing the PR) squash all commits into one?

Regarding the bug, can you post the steps needed to reproduce?

**Comment by andiwand** [comment]
oh my god. im sorry but i failed doing this. i was able to squash all my commits, but with the pull from rewrite it crashed. i thought i can just recreate my branch with rewrite pulled from beginning. but no.

so i got the my branch here: https://github.com/andiwand/pilight/tree/feature/csmacd. but i fear this pr is broken. so sorry. :(

**Comment by andiwand** [comment]
ad bug:
- compile current rewrite
- run "pilight-daemon -D"
- connect to the webinterface
- trigger a single state change e.g. light on
- cpu load gets ~95%
- trigger a second state change e.g. light off
- normalized cpu load (~30% for me)

**Comment by CurlyMoo** [comment]
There was nothing wrong with this PR when you removed the csmacd branch...

**Comment by andiwand** [comment]
my branch was forked from development and later i merged rewrite into it. i tried to squash ist but got this mass of changes (+9,505 −2,870). i think the right way would have been to leave the merge commit and squash the rest... but don't know for sure.

again, i'm really sorry about this...

**Comment by wo-rasp** [comment]
I think in no case should rewrite be merged with development.
In my opinion you should have rebased your feature/csmacd branch on rewrite.
Assuming that feature/csmacd was based on development, you should have changed to feature/csmacd and from there issued a "git rebase rewrite".
In that case git would have taken all commits from feature/csma/cd that are not yet part of rewrite, and would have created a new commit based on the HEAD of rewrite, and that new commit is now the HEAD of feature/csmacd.

**Comment by andiwand** [comment]
thanks for the clarification!

**Comment by wo-rasp** [comment]
It's a pleasure, actually, i have several pull requests open for integration with the development branch, that i currently keep maintained by constantly merging development into my local repository. As others may have as well to maintain their work for rewrite, i have created a thread in the forum.

**Comment by CurlyMoo** [comment]
Can you list those PR's?

**Comment by wo-rasp** [comment]
#200 (somfy).
I just checked the oregon21 status, due to the fact that oregon21 is based on Somfy, and requres more changes in daemon.c, i never forwarded that one (oregon21 can partly restore missing pulses and needs to manipulate individual pulses received before processed further).

The reason I do not proceed right now i want to ge ahead in steps:
1st - integrate somfy_step
2nd - update somfy_step with the code changes from somfy_release (without the detailled debug statements from somfy_release, i want to keep that special somfy_release version myself in case users have great difficulties and i do need additional debug information for helping them), however Ii agree to not having them in the mainstream branch
3rd - I want to rebase the somfy_step work, once it is integrated into development, on rewrite. This is the moment I do not need to keep the development version anymore.

Once somfy_step is mainstream i will rebase oregon21 on the mainstream development branch, and after acceptance of the development branch, i will rebase oregon21 on rewrite.

Aforementioned steps are pretty much based on what I proposed on the forum in the thread 
- HowTo Move your 3rd party code code from development to rewrite

In my opinion those easy to follow steps are helpful for all of us and I would like to get more feedback in the forum, so it evolves into a HowTo document we can put into the manual.

**Comment by CurlyMoo** [comment]
So you first want to merge into development and then rewrite?

**Comment by wo-rasp** [comment]
Yes, the current code is ready for getting merged with development. Once that merge is done,
I fetch "upstream development" into origin/development and fetch "upstream rewrite" into origin/rewrite.
Now my branch origin/somfy_step is obsolete, so I can rebase origin/somfy_step on origin/rewrite, test it, commit it, push it to "origin somfy_step" and issue the pull request for "origin somfy_step" for getting merged with rewrite.

**Comment by andiwand** [comment]
should have done that too, because my implementation for current
development is more or less lost now.

**Comment by CurlyMoo** [comment]
Merge into development can be done quick. I have done most work already locally.

**Comment by wo-rasp** [comment]
Typically it is only lost if you have deleted your complete local git directory or you did a garbage collection in an attempt to recover.

When you have used git commands to delete a commit, that commit is not immediately deleted but it is kept in dangling state.
The problem is the #shacode (hash or whatever you want to call that hexanumber) in order to access those files.
 
Try “git fsck --lost-found”, to get a list of old commits.

 

Use checkout #shacode and check If you can find your old revision.

Git is telling you what to do next to get from detached mode back to an active branch with all those files.

 

Von: Andreas Stefl [mailto:notifications@github.com] 
Gesendet: Donnerstag, 17. März 2016 00:32
An: pilight/pilight
Cc: wo-rasp
Betreff: Re: [pilight] implement media access control by csma and csma/cd (#250)

 

should have done that too, because my implementation for current
development is more or less lost now.

**Comment by andiwand** [comment]
thanks for the information! i got the code on one of my rpis... so i could
create a new branch with this code based on development. is it worth to do
that or would you even merge it @CurlyMoo if rewrite will be live soon?

**Comment by wo-rasp** [comment]
If I understand curlymo correctly he does not intend to incorporate that feature into development any more, thus I would keep my local copy of development, and continue for the public version on the rewrite branch. (i have now set up on my machine several local repositories: /home/pi/dev and /home/pi/rewrite).

**Comment by CurlyMoo** [comment]
@andiwand, your change will be merged into rewrite, the one from @wo-rasp can be merged into development because i already implemented the logic locally and it can be more easily ported to rewrite.

**Pull request closed without merging**
