### PR TITLE
Add output filter and formatting options to pilight-raw.

### PR DESCRIPTION
**Pull request by yablacky**
--minpulses n Allows to suppress output of too short pulse sequences.
 --pulsesperline n Adds a line break after n printed pulses in a line.
Both options, if given, imply the --linefeed option. With these options
the output also includes a counter of total pulse sequences received.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you do these fixes on the rewrite branch? And maybe help me with making the rewrite branch stable enough so we can me it developmental?

**Comment by yablacky** [comment]
...making the rewrite branch stable enough so ... what? Sorry I didn't understand (me = make?).

Haven't used the rewrite branch before. Could you give me short advice in when to make pull requests on the development branch and when on rewrite branch?

**Comment by CurlyMoo** [comment]
I've released a branch containing the code of a big rewrite. The commit message(s) of that branch should tell more. That code should become the new development soon and this development should be halted until then.

**Comment by yablacky** [comment]
ok, I got the rewrite branch and the changes made.
it compiles with a handful of warnings. Some of which I fixed already (in wiringX) and some warnings are new, some were already in development as rewrite was created.
Now, what do you mean with "stable enough"?

**Comment by CurlyMoo** [comment]
I've been working on that code for months and it contains several fundamental fixes. The point it that i'm sure that code is not working as stable as the developmental code, because i was the only one testing it.

All developmental code has been merged in rewrite already.

I want to merge all rewrite code into development asap so users running that code can use it as well.

**Comment by yablacky** [comment]
I think that I'm not able to help testing protocols for hardware. I have only one and that is not even supported yet... (that's why I work on pilight-raw... ;-) Maybe the daemon is where I can help testing a little.
On the other hand and IMHO, functional changes in rewrite-branch are not dramatically different from development-branch. I can't speak for the added protocols but the remaining stuff to me seems no less stable than development when rewrite started.

**Comment by CurlyMoo** [comment]
If that's true than just start using the rewrite branch :)

**Comment by yablacky** [comment]
The other possibility is you to merge rewrite into development and continue there. I can of  course add/fix things in rewrite as well. The contribution rules should be changed so that other contributors also know that actually rewrite is the base for contribution (and no longer development).

**Comment by wo-rasp** [comment]
I would appreciate of getting at least the following 4 open pull requests, supposed to fix stability issues, integrated into rewrite:
- 231
- 238
- 240
- 243
Can we get them closed ASAP in development ?:
In addition I have some difficulties to understand the current git log, i would have expected that the rewrite branch has a root with development some time ago, but looking at the log it seems to be rebased onto the tip of development. I have difficulties to envision that some of the open pull requests will seemlessly integrate into rewrite and I would appreciate if this could be addressed as well.

**Comment by CurlyMoo** [comment]
> The other possibility is you to merge rewrite into development and continue there.

The problem is that `development` is automatically compiled into the nightly deb packages, windows installer and openwrt package. I know it's confusing :smile:

Merging rewrite into development would mean a partly loss of functionality:
1. Windows not supported yet.
2. Z-Wave doesn't work.
3. Probably less stable, because of unknown bugs.

> Looking at the git log rewrite is the new HEAD of development, strictly spoken it does not need to get merged into development,

Rewrite has not been rebased or anything. What i did was working on rewrite the last couple of months. What i did last weekend was:
1. `git stash`
2. `git pull origin development`
3. `git stash pop`
4. Fix all conflict because of differences between development and rewrite.
5. Commit and push changes.

The rewrite code starts at commit `The new base code of the pilight v7 rewrite`, the rest is merging of older commits that were present in development.

So nothing different than a normal workflow in which you merge to parralel branches into one.

> Can we get them closed ASAP in development ?:

I will look into this ASAP :+1:

**Comment by yablacky** [comment]
Shouldn't rewrite be splitted into smaller parts (branches) of which many can be merged into development with low risk?

**Comment by pilino1234** [comment]
> Shouldn't rewrite be splitted into smaller parts (branches) of which many can be merged into development with low risk?

That would be quite difficult I think, 

> Due to the impact these new patterns have in
the pilight codebase, intermediate releases
where not an option. That would have resulted
in a incomplete and non-usable pilight version.

**Comment by CurlyMoo** [comment]
All of these (https://github.com/pilight/pilight/pull/245#issuecomment-190432810) are merged

**Comment by pilino1234** [comment]
Needs a bit of rebasing, any update on this @yablacky?

**Pull request merged**
