### PR TITLE
Kernel 4.9.x compatibility update wiringx

### PR DESCRIPTION
**Pull request by wo-rasp**
Replaces PR #324 
https://forum.pilight.org/Thread-Boot-from-USB?pid=20427#pid20427

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Merge commits please.

**Comment by wo-rasp** [comment]
Commit c2345a2 (mail.c) and d8c2dd0 (contact protocol) are not supposed to be part of this pull request again, will be submitted separately.
Only ba59f34 (syncing upstreeam and local development branch) and 0ea0531 (Kernel 4.9 wiringx) are.

**Comment by CurlyMoo** [comment]
I know. Awaiting for the commits to be merged into one.

**Comment by wo-rasp** [comment]
I do need to get rid of the contact protocol first ....

Von meinem iPhone gesendet

**Comment by wo-rasp** [comment]
Cleaned up pull request, only kernel 4.9 modifications

**Comment by CurlyMoo** [comment]
I will merge both wiringX and pilight PR at the same time. Can you do the wiringX as well?

**Comment by wo-rasp** [comment]
As discussed on the forum I do need to do some regression testing first.

Von meinem iPhone gesendet

**Comment by CurlyMoo** [comment]
Take your time.

**Comment by wo-rasp** [comment]
Okay. Cleanup is done. Current HEAD of development (9249fd0) is the root for the 3 branches hosting the modifications for mail.c (original commit sha), wiringX (new sha due to removal of contact protocol), and the new contact protocol (work in progress).

* 0882e74 (origin/dev_kernel49, dev_kernel49) Kernel 4.9x compatibility update for wiringX interface raspberry Pi https://forum.pilight.org/Thread-Boot-from-USB?pid=20427#pid20427
| * a92e5d2 (HEAD, origin/dev_gs_iwds07, dev_gs_iwds07) Creation of gw-iwds07 window contact protocol https://forum.pilight.org/Thread-gs-iwds07-window-sensor?pid=20389#pid20389
|/
| * c2345a2 (origin/dev_mail) Improved status checking in mail.c in accordance to RFC requirements
|/
*   9249fd0 (upstream/development, origin/development, origin/HEAD, development) Merge pull request #325 from wo-rasp/development

**Comment by wo-rasp** [comment]
What do you mean with wiringX ?

**Comment by CurlyMoo** [comment]
>What do you mean with wiringX ?

Seriously 😲 That's the other big project by pilight that drives the whole GPIO interface for all supported platforms. That is decoupled from pilight and developed seperately:
https://github.com/wiringx
www.wiringx.org

**Comment by wo-rasp** [comment]
Will check it out.

Von meinem iPhone gesendet

**Comment by ezar** [comment]
Hi,
Merged? Please I updated 4.9.x kernel because it's default...

**Comment by CurlyMoo** [comment]
The comments are not resolved yet so...

**Comment by wo-rasp** [comment]
PR for wiringX issued as well

**Pull request merged**
