### PR TITLE
Add Heitech switch protocol

### PR DESCRIPTION
**Pull request by mel0en**
Add switch protocol, adjusted to the latest nightly (08-05-2015.

### CODE REVIEW

**Comment by mel0en** [comment]
Apologies, forgot to rebase.

**Comment by CurlyMoo** [comment]
You don't need to close. Just rebase.

**Comment by mel0en** [comment]
Rebase doesn't like me... Is this enough: https://patch-diff.githubusercontent.com/raw/pilight/pilight/pull/178.patch

**Comment by CurlyMoo** [comment]
Depens on you. You're not listed at the contributor on github if i merge it myself.

**Comment by mel0en** [comment]
I don't mind :)

**Comment by CurlyMoo** [comment]
Merged. Can you create the wiki page for it.

**Pull request closed without merging**
