### PR TITLE
MaxiTronic switch support

### PR DESCRIPTION
**Pull request by puuu**
Protocol is similar to elro_800_switch, but has a additional Med bit in the ID part.

Transmitter and switch has no dip switches.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can't we make elro_800_switch more versatile?

**Comment by puuu** [comment]
Did you have any suggestion? I don't know if it is a good idea to change `systemcode` from number to string.

**Comment by CurlyMoo** [comment]
So let's start with a forum post describing the protocol. I now have to guess what you implemented and that not something i do best.

**Comment by puuu** [comment]
Close, because PR #282 is merged.

**Pull request closed without merging**
