### PR TITLE
BMP180/BMP085 Barometric Pressure and Temperature Sensor 

### PR DESCRIPTION
**Pull request by hstroh**
I've implemented a new protocol for sensor BMP180 (and its predecessor BMP085) which provides barometric pressure in hPa and temperature in °C. The algorithm for pressure and temperature measurement is based on the specification in the [official datasheet](https://ae-bst.resource.bosch.com/media/products/dokumente/bmp180/BST-BMP180-DS000-09.pdf). The implementation has been successfully tested using the sample values provided in the referenced sheet. 

I've added an option to display (barometric) pressure in the web UI for weather protocols. Pressure is displayed iff option `show-pressure` (which is a GUI setting) is set to `1`.The value to display is provided via option `pressure`. For proper display I've provided a new icon `pressure.png` which is a modification of `humi.png`.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Please merge into development with 1 commit.

**Comment by CurlyMoo** [comment]
Also don't include the protocols*.h files.

**Comment by hstroh** [comment]
Sorry, your second post didn't reach me before creating another pull request. Is the new request okay although it contains the protocols*.h files?

**Comment by hstroh** [comment]
I realized the wrong target branch of this request myself but you outsped me in closing it. Thanks for your guidance and please bear with me as I'm still new to Git.

**Comment by CurlyMoo** [comment]
Of course. I also could have merged it myself but that doesn't have my preference. A tip is also to test this on local repositories instead of these official ones.

**Pull request closed without merging**
