### PR TITLE
Add support for GS WDS07 door window sensor

### PR DESCRIPTION
**Pull request by 1technophile**
Full credit to  CurlyMo & wo_rasp
Discussed here https://forum.pilight.org/showthread.php?tid=2952&page=3
and here https://github.com/pilight/pilight/pull/337

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Thanks for this PR. Can you do a PR with unittest for the rewrite branch as well?

**Comment by 1technophile** [comment]
Yes I will add to rewrite branch this PR with Unit tests also

**Comment by 1technophile** [comment]
Do you have some idea about how to recover the link to the fork. After some try, tests and at final a question to github, it doesn't seems to be possible. Here is the answer:

> HI Florian,
> 
> It isn't possible to reconnect a PR to a deleted fork I'm afraid. When a repository is deleted, all open Pull Requests are disconnected from the non-existing repository. Once the link is broken, it's removed permanently and can't be reconnected afterwards.
> 
> I'd suggest closing the existing Pull Request and creating a new one using your current fork.
> 
> Sorry we couldn't be of more help at this time. Feel free to come back to me if there's anything else you need.
> 
> Cheers

**Comment by CurlyMoo** [comment]
> Do you have some idea about how to recover the link to the fork.

Why did you remove that fork in the first place?

**Comment by 1technophile** [comment]
There was some mistakes on the first fork I made and I wanted to rebegin from a fresh one. Quick solution but bad solution.

**Comment by CurlyMoo** [comment]
>There was some mistakes on the first fork I made and I wanted to rebegin from a fresh one. Quick solution but bad solution.

I sadly think the github helpdesk is right.

**Pull request closed without merging**
