### PR TITLE
adding travis configuration for continuous integration build

### PR DESCRIPTION
**Pull request by behrisch**
I just set this up for testing the pilight build but maybe it is useful for the project in general. For the build results see: https://travis-ci.org/behrisch/pilight/

### CODE REVIEW

**Comment by CurlyMoo** [comment]
What the use of this over the rewrite branch CI?

**Comment by behrisch** [comment]
Sorry, I did not notice this one.

**Comment by behrisch** [comment]
I wanted to have a CI for staging so that I can test easier when implementing the new module based on staging. Furthermore I wanted to check a little how the PR process works and if I can do a somehow "minimal build" (my travis file is really small and does not depend on external scripts). Also my impression was that there is something missing from the installation instructions (at least they do not mention installing luajit for self compiling) and I wanted to check with travis whether it is only my computer.

**Comment by CurlyMoo** [comment]
Please do not use the official pilight repositories for testing purposes. That being said. If you believe something is missing somewhere, feel free to fix it in a new PR.

**Comment by behrisch** [comment]
Sorry about that. I really thought a CI build for staging could help until you showed me the one in rewrite.

**Comment by CurlyMoo** [comment]
I think it could still help, that's why i wanted to know your ideas on this. One thing it could help with is automatic packaging.

**Pull request closed without merging**
