### PR TITLE
Livolo protocol (sending only) [rewrite branch]

### PR DESCRIPTION
**Pull request by leppa**
As requested in #339, here's my change on top of the `rewrite` branch with two basic tests.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
The tests will be used in the future to make sure protocols keep working in case i will change the protocol code. Are you confident you've added enough tests?

**Comment by leppa** [comment]
There's not much to test, actually, because it's send only and the protocol is simple.

**Comment by CurlyMoo** [comment]
One thing i forgot. Can we update the license to MPLv2 in both development and rewrite?

**Comment by leppa** [comment]
No problem. Feel free to update it.

**Comment by CurlyMoo** [comment]
Can you maybe do a new PR with the new license?

**Pull request merged**
