### PR TITLE
Quigg gt7000 sw

### PR DESCRIPTION
**Pull request by wo-rasp**
Updated quigg_gt7000_switch and quigg_gt7000_screen (quigg switch with dimm function).
In the old protocol the id was handled in reverse order, this is corrected now.
id handling: old 2816 -> new 13, old 1792 -> new 14, old 3840 -> new 15, old 128 -> new 16, ....
protocol name has changed from
quigg_switch to quigg_gt7000_switch
quigg_screen to quigg_gt7000_screen

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Still too many commits.
- I just want a single one with all updates included.
- I don't want quigg_screen. That one will be removed from stable anyway until properly implemented.
- quigg_gt7000_sw is called quigg_qt7000. You could have already seen that when you compared your branch against mine.
- I don't want core changes until properly discussed.

So can you **please** review your commits. The pilight pull-request list is a mess already.

**Comment by wo-rasp** [comment]
The decision is fine with me. The wiki corresponds to quigg_gt7000 and the old id numbering.

 

At a 1st glance 35 commits seem to be quite outraging, however

24 are from upstream/development

1 for GT_1000 from rinusw from upstream/development

6 for merging pilight development into origin repository,

4 from me (1 for cleanup, 1 to pull modifications back from my testbed into origin, 1 is internal for switching branches, 1 for submission of pull request)

 

I understand that it is beneficial to split submssions into manageable bits and pieces,

however working on several protocols in parallel basically either requires to stash or to commit work in progress.

 

Von: CurlyMoo [mailto:notifications@github.com] 
Gesendet: Montag, 2. Februar 2015 00:38
An: pilight/pilight
Cc: wo-rasp
Betreff: Re: [pilight] Quigg gt7000 sw (#139)

 

Still too many commits.

*	I just want a single one with all updates included.
*	I don't want quigg_screen. That one will be removed from stable anyway until properly implemented.
*	quigg_gt7000_sw is called quigg_qt7000. You could have already seen that when you compared your branch against mine.
*	I don't want core changes until properly discussed.

So can you please review your commits. The pilight pull-request list is a mess already.

—
Reply to thxxxis email directly or view it on GitHub <https://github.com/pilight/pilight/pull/139#issuecomment-72391664> .  <https://github.com/notifications/beacon/AG9MV3RRbbxfvqAu1mZn7Om6IQyCncijks5nnrBsgaJpZM4DaIwO.gif>

**Comment by CurlyMoo** [comment]
You can of course work on as much protocols you need in your own branch, as long as you upload the changes you want to push to a separate branch before you go upstream.

**Comment by CurlyMoo** [comment]
And please ask for help if you notice these issues.

**Pull request closed without merging**
