### PR TITLE
Created ISNOT operator

### PR DESCRIPTION
**Pull request by NiekD**
This operator takes two string operands (just like the IS operator) and
evaluates to TRUE if the operands are NOT equal.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Isn't this possible in another way?

**Comment by NiekD** [comment]
Op 19-9-2015 om 22:22 schreef CurlyMoo:

**Comment by wo-rasp** [comment]
I t is beneficial to have this operator.
Example: On s_mfy, we have the 3 button interface and three states: Down, My ( Stopped), Up.
If i want to implement a rule to move the screen down, i currently need to test for MY and UP, if i want to move it down, with ISNOT, i simply can ask with one stetement ifnot(DOWN) -move DOWN ... even easy to understand.

**Comment by NiekD** [comment]
Ofc I agree ;). 
I myself am using the COLOR option of generic_label devices as variables.  If such a "variable" can have more than 2 different values, I am using the ISNOT operator to check for the absence of a specific value. If I would only have the IS operator I would have to check for the presence of any value the "variable" might have. 
Simple example: values can represent the conditions CLOSED, OPEN and LONG OPEN. With IFNOT I can test if the condition is not CLOSED, otherwise I would need to check for both OPEN and LONG OPEN.

**Comment by wo-rasp** [comment]
The ISNOT operator is of more use than the the IS operator.
If I have two different states, IS and ISNOT are equivalent.
If I have three different states, I can use one ISNOT operator to rule out the two other conditions.
I propose to get the operator integrated.

**Pull request merged**
