### PR TITLE
Updated librairies in webgui 

### PR DESCRIPTION
**Pull request by TopdRob**
New pull request against development branch

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Actually push according to `all` our rules.

**Comment by TopdRob** [comment]
Dear CurlyMoo,

I understood you don't have time for teaching. But can you please be some more specific what rule I missed?

**Comment by CurlyMoo** [comment]
Rule 7.

**Comment by CurlyMoo** [comment]
Especially don't close the PR but resolve it.

**Comment by TopdRob** [comment]
Almost there. I have done the rebase action however I cant't push

root@RaspberryPi:/home/pi/github/pilight# git push -f pilight HEAD:development
Username for 'https://github.com': TopdRob
Password for 'https://TopdRob@github.com':
remote: Permission to pilight/pilight.git denied to TopdRob.
fatal: unable to access 'https://github.com/pilight/pilight.git/': The requested URL returned error: 403

**Comment by pilino1234** [comment]
That's because you can't push to pilight/pilight, you need to push to
your fork.

**Pull request closed without merging**
