### PR TITLE
Broken sending via pilight-usb-nano

### PR DESCRIPTION
**Pull request by alcoheca**
Depends on similar PR for pilight-usb-nano

### CODE REVIEW

**Comment by CurlyMoo** [comment]
I ofc knew you were going to point to these lines :smile: I have to check if this was all places i implemented the optimalizations, and if your PR was sufficient to revert them.

**Comment by alcoheca** [comment]
Some optimization.. :)

**Comment by CurlyMoo** [comment]
Could you control your devices with this fix?

**Comment by CurlyMoo** [comment]
Can you also increase the version number to `0.12`? And then squash those two commits into one.

**Comment by alcoheca** [comment]
Of course

**Comment by alcoheca** [comment]
and yes the devices now work.

**Comment by CurlyMoo** [comment]
Awesome!

**Pull request merged**
