### PR TITLE
add "battery low" state to kerui protocol

### PR DESCRIPTION
**Pull request by mwalliczek**
see PR #457

### CODE REVIEW

**Comment by CurlyMoo** [comment]
What about:
```c
static void createMessage(int unitcode, int state, int state2, int state3, int state4, char **message) {
        int x = 0;
        x = snprintf((*message), 255, "{\"unitcode\":%d,", unitcode);
	if(state4 == 0) {
	        x += snprintf(&(*message)[x], 255-x, "\"state\":\"opened\"");
	        x += snprintf(&(*message)[x], 255-x, "\"battery\":\"high\"");
	}
        else if(state == 0) {
	        x += snprintf(&(*message)[x], 255-x, "\"state\":\"closed\"");
	        x += snprintf(&(*message)[x], 255-x, "\"battery\":\"high\"");
        }
        else if(state2 == 0) {
	        x += snprintf(&(*message)[x], 255-x, "\"state\":\"tamper\"");
	        x += snprintf(&(*message)[x], 255-x, "\"battery\":\"high\"");
        }/*
        else if(state3 == 0) {
	        x += snprintf(&(*message)[x], 255-x, "\"state\":\"not used\"");
	        x += snprintf(&(*message)[x], 255-x, "\"battery\":\"high\"");
        }*/
	else{
	        x += snprintf(&(*message)[x], 255-x, "\"battery\":\"low\"");
	}
	x += snprintf(&(*message)[x], 255-x, "}");
}
```
```c
options_add(&kerui_D026->options, "b", "battery", OPTION_HAS_VALUE, DEVICES_VALUE, JSON_STRING, NULL, NULL);
```

**Comment by mwalliczek** [comment]
Good suggestion, thanks!

**Comment by CurlyMoo** [comment]
Did you already test this in a working environment?

**Comment by mwalliczek** [comment]
I did a test with this code in working environment (backported to 8.1.4) - turns out, there is a problem with existing configuration; pilight complains about missing property "battery". It does not matter if I use OPTION_HAS_VALUE or OPTION_NO_VALUE. Do you have any idea?

**Comment by CurlyMoo** [comment]
Can you update the staging PR accordingly so i can check with that version myself?

**Comment by mwalliczek** [comment]
Done

**Comment by CurlyMoo** [comment]
Can you add a battery = 0 unittest

And did you test the unittests you made / adapter yourself?

**Comment by mwalliczek** [comment]
I was just able to add a unittest with battery = 0.

**Pull request merged**
