### PR TITLE
Improved status checking in mail.c in accordance to RFC requirements

### PR DESCRIPTION
**Pull request by wo-rasp**
After 250 the remote site may respond with various 4xx and 5xx error messages, most notably 452 is not handled, typically this will lead to high CPU load and pilight terminates itself.
This pull request will handle all 4xx and 5xx reponses as a permanent failure and terminate the request, in very rare cases it may be that a 552 request, that should be handled as a temporary failure is now treated as a permanent one, but I consider this minor compared to the termination of the daemon, in particular under the consideration that a correct handling of 552 errors is pretty complex.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you do this PR in rewrite?

**Comment by CurlyMoo** [comment]
I already changed the base. Can you also remove the contact protocol from this commit?

**Comment by wo-rasp** [comment]
Hmm, i am a bit curious how the gw-iwds07 protocol made it to this pull request, it was definitely not intended, as the protocol has not yet passed all tests with real devices. Looking at the number of conflicts to resolve, i propose to issue a separate pull request using the rewrite branch.

**Comment by CurlyMoo** [comment]
I would just do some git magic so you don't have to close this PR.

**Comment by wo-rasp** [comment]
I don't think that it will work in this particular case.
1st - i have made my changes by mistake in my development branch and not in a new branch dev_mail
2nd - your repo is now pointing to rewrite, but my development branch is not, thus there are many unresolved conflicts
3rd - after submitting my PR, i added the contact protocol to my development branch, however have not yet issued a PR ....
--------
I have cleaned up my repo, as i had made some changes not in the correct branches.....
The changes for wiringX are now part of my dev_kernel49 branch - PR issued
The mail.c changes for your development branch are part of my dev_mail branch - uploaded
The mail.c changes for your rewrite branch are now part of my rewrite_mail branch - uploaded
The new gs_iwds07 contact protocol is now part of my dev_gs_isds07 branch - uploaded

Am I right that you do need to change for this pull request first the remote tracking directory from wo-rasp:development to wo-rasp:rewrite_mail ? And only after that happened i can issue the update for my PR ?

**Comment by CurlyMoo** [comment]
I can only change the target branch, not the source.

**Comment by wo-rasp** [comment]
I used the wrong source branch. Closing to re-open with correct branch in my repository.

**Pull request closed without merging**
