### PR TITLE
add kerui protocol

### PR DESCRIPTION
**Pull request by mwka**
new protocol KERUI D026 door sensor, adapted the code from pull request #350

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Can you fix your PR to be compliant with the new staging base?

**Comment by CurlyMoo** [comment]
Looks good. Can you add a manual page and also add a PR to the rewrite branch which includes a unittest for this protocol.

**Comment by mwka** [comment]
Where can I find information about setting up unit tests at the rewrite branch and executing them?

**Comment by CurlyMoo** [comment]
Is our forum conversation enough answer?

**Comment by CurlyMoo** [comment]
Can you change all licenses to MPLv2?

**Pull request merged**
