### PR TITLE
Added Phillips Hue protocol that connects to Philips Hue Bridge.

### PR DESCRIPTION
**Pull request by ma-ca**
Added Phillips Hue protocol that connects to Philips Hue Bridge Rest API and controls Philips Hue bulbs. The protocol polls the status from the Bridge every minute to update the device values in pilight.

The Philips Hue Rest API is described here:

http://www.developers.meethue.com/documentation/getting-started

http://www.developers.meethue.com/documentation/core-concepts

The protocol philipshue allows `pilight-send` and `pilight-control` to control all available settings for the bulbs. 

The GUI, for now, has the limitation to only show a dimmer switch for on off and to set the dimlevel (brightness) for each bulb.

`$ pilight-send -p philipshue -H`
Usage: pilight-send -p philipshue [options]
         -H --help                      display this message
         -V --version                   display version
         -p --protocol=protocol         the protocol that you want to control
         -S --server=x.x.x.x            connect to server address
         -P --port=xxxx                 connect to server port
         -C --config                    config file
         -U --uuid=xxx-xx-xx-xx-xxxxxx  UUID

```
    [philipshue]
     -i --bridgeip=<ipaddress>              Philips Hue Bridge IP Address
     -l --lightid=<lightid>                 lightid (1,2,3,..)
     -u --username=<username>               username for bridge api
     -o --on=<true|false>                   set light state on to true|false
     -b --bri=<0..254>                      brightness of a light from 0 to 254, this value is changed by dimlevel
     -h --hue=<0..65535>                    hue color value red=0 / yellow=12750 / green=25500 / blue=46920 / purple=56100 / red=65280
     -s --sat=<0..255>                      saturation from 0 to 255
     -e --effect=<none|colorloop>           effect none|colorloop (endless color looping mode until it is stopped by sending none)
     -x --x=<0..0.9999>                     x value in xy color points
     -y --y=<0..0.9999>                     y value in xy color points
     -c --ct=<153..500>                     color temperature (warmest color is 500)
     -a --alert=<none|select>               alert=select makes the light do a blink in its current color
     -g --group=<0..>                       running on group of lights. The group must have been created before (group 0 always includes all lights)
     -z --scene=<scene-id>                  apply a predefined scene id (use option --resource=scenes to list all scenes on hue bridge)
     -r --resource=<resource>               list resource lights|groups|config|schedules|scenes|sensors|rules
     -t --on                                turn light or group on
     -f --off                               turn light or group off
     -n --newuser                           create and authorize user on Hue Bridge. Press link button on bridge and run pilight-send -p philipshue --bridgeip=<ip> --newuser again.
```

First a username must be created and authorized on the bridge by pressing the link button and running the command:

`$ pilight-send -p philipshue --bridgeip=192.168.1.252 --newuser`
 pilight-send: NOTICE: Create and authorize new user for pilight on Hue Bridge ...
 pilight-send: NOTICE: philipshue - post data = {"devicetype":"pilight"} to url http://192.168.1.252/api
 pilight-send: NOTICE: response from hue bridge = [{"error":{"type":101,"address":"","description":"link button not pressed"}}]
 pilight-send: NOTICE: description = link button not pressed
 pilight-send: NOTICE: ----> Press Link button and run again pilight-send -p philipshue --ip=192.168.1.252 --newuser

(Now pressing the link button)

`$ pilight-send -p philipshue -i 192.168.1.252  --newuser`
 pilight-send: NOTICE: Create and authorize new user for pilight on Hue Bridge ...
 pilight-send: NOTICE: philipshue - post data = {"devicetype":"pilight"} to url http://192.168.1.252/api
 pilight-send: NOTICE: response from hue bridge = [{"success":{"username":"29b7e422ee6f973bc97b3e1f3269a3"}}]
 pilight-send: NOTICE: ----> Successfully created and authorized username =  29b7e422ee6f973bc97b3e1f3269a3 <--- Use this username

Examples:

List all bulbs on the bridge:

`$ pilight-send -p philipshue --bridgeip=192.168.1.252 --username=29b7e422ee6f973bc97b3e1f3269a3 --resource=lights`

List all scenes on the bridge:

`$ pilight-send -p philipshue --bridgeip=192.168.1.252 --username=29b7e422ee6f973bc97b3e1f3269a3 --resource=scenes`
 pilight-send: NOTICE: philipshue - get data http://192.168.1.252/api/29b7e422ee6f973bc97b3e1f3269a3/scenes
 pilight-send: NOTICE: 497b50d84-on-0 = {"name":"Sunset on 0","lights":["1","2","3"],"active":true}
 pilight-send: NOTICE: ac637e2f0-on-0 = {"name":"Relax on 0","lights":["1","2","3"],"active":true}
...

Apply a scene:

`$ pilight-send -p philipshue --bridgeip=192.168.1.252 --username=29b7e422ee6f973bc97b3e1f3269a3 --scene=497b50d84-on-0`

Turn all lights on:

`$ pilight-send -p philipshue --bridgeip=192.168.1.252 --username=29b7e422ee6f973bc97b3e1f3269a3 --group=0 -t`

Turn all lights off:

`$ pilight-send -p philipshue --bridgeip=192.168.1.252 --username=29b7e422ee6f973bc97b3e1f3269a3 --group=0 -f`

Set full brightness red on light 2:

`$ pilight-send -p philipshue --bridgeip=192.168.1.252 --username=29b7e422ee6f973bc97b3e1f3269a3 --lightid=2 --bri=255 --sat=255 --hue=0`

Add the following device in /etc/pilight/config.json to use pilight-control.

```
    "devices": {
            "Hue1": {
                    "protocol": [ "philipshue" ],
                    "id": [{
                            "bridgeip": "192.168.1.252",
                            "username": "29b7e422ee6f973bc97b3e1f3269a3",
                            "lightid": 1
                    }],
                    "on": "false",
                    "bri": 254,
                    "hue": 8625,
                    "sat": 252,
                    "effect": "none",
                    "x": 0.5837,
                    "y": 0.3879,
                    "ct": 500,
                    "alert": "select",
                    "dimlevel": 15,
                    "group": 0,
                    "scene": "0",
                    "state": "off"
            }
    }
```

Turn light 1 to red.

`$ pilight-control -d Hue1 -s on -v hue=65280`

Turn all lights on

`$ pilight-control -d Hue1 -s on -v group=0`

Turn all lights off

`$ pilight-control -d Hue1 -s off -v group=0`

Apply scene

`$ pilight-control -d Hue1 -s off -v scene=497b50d84-on-0`

Add gui in config.json

```
    "gui": {
            "Hue1": {
                    "name": "Light1",
                    "group": [ "Hue Lights" ]
            }
    }
```

### CODE REVIEW

**Comment by CurlyMoo** [comment]
Is it possible to control these lights without using the bridge? Just curious?

**Comment by ma-ca** [comment]
That is possible.
http://www.developers.meethue.com/documentation/how-hue-works
> Overview > 4. Lights - ...They are connected to the bridge via an open standards protocol called ZigBee Light Link. If you’d like to start a project which talks directly to the bulbs that’s possible but you’ll need to enroll in the ZigBee developers program – for more info see www.zigbee.org.

**Comment by CurlyMoo** [comment]
> That is possible.
http://www.developers.meethue.com/documentation/how-hue-works

Are you interested to do so?

**Comment by ma-ca** [comment]
No, that would require some ZigBee module instead of the bridge. Also, without a bridge, other Apps would not be able to use the bulbs.
The benefit of having pilight controlling the bulbs (using the bridge) is when a wall switch turns off the bulbs. Then pilight can turn on the wall switch. That turns on the bulbs in their default state full bright white. Until now, I used a custom script with curl to put the bulbs into the desired state. This is now possible with pilight.

**Comment by CurlyMoo** [comment]
> No, that would require some ZigBee module instead of the bridge.

I know, but are you interested in building support with the modules. I can pay for it ofc.

**Comment by ma-ca** [comment]
I need to think about it, but I may not have enough time for doing that.

**Comment by wo-rasp** [comment]
The Hue Bridge is the center piece of a Philips Hue Remote LED system, controlling up to 50 devices. Supporting that is IMHO already a big step into a user friendly direction and enhancement of pilight's capabilities.
Adding the Zigbee protocol later on should not stop us at this point ....
Do we want to add that protocol ? If yes i would volunteer to collapse the work into one single commit and to setup the WIKI page based on the above information.

**Comment by wo-rasp** [comment]
Typically the Hue Bridge is part of a so called "Starter Kit" together with the light bulbs.
The Hue Bridge is required if a user wants to control the light bulbs via the standard Mobile Phone Apps (iOS, Android, WP 8.1 or higher, W10) or via Hardware Devices.
PR #216 supports all features as described above, the GUI supports mono color lamps, including dim functionality.
The only issue i found so far is the REGEX for the user name, I recommend to remove the regex checking for the user name, as on my device the minus sign "-" is part of the user code and I assume that the current limitation to letters is not correct.
I recommend to add the protocol to the development branch.

**Comment by ma-ca** [comment]
http://www.developers.meethue.com/documentation/getting-started
> Currently it is possible to create your own usernames in the bridge (e.g. “newdeveloper”), however, this option will be removed in future bridge versions,  so we need to use the randomly generated username that the bridge creates for you.

**Comment by wo-rasp** [comment]
Okay, based on your desccription i have created a wiki entry.
Hue users who have mastered to integrate their own App on their mobile phone, should be able to setup the pilight environment as well.
I so propose to integrate this protocol into the development V7 branch, as my experience was positive, no hurdles or issues (except the REG-EX subject, when usernames created by the Hue bridge are used.

**Comment by CurlyMoo** [comment]
@wo-rasp told me to reconsider this API protocol. So here i am. 

First question. Why does this protocol use its own http function and not the function already in the pilight library?

**Comment by ma-ca** [comment]
The Hue bridge API needs also HTTP PUT and DELETE but pilight has only HTTP GET and POST.

**Comment by pilino1234** [comment]
So let's extend the pilight HTTP functionality 😄

**Comment by wo-rasp** [comment]
Let us get started and based on demand and  add functionality as part of development

Von meinem Mobiltelefon gesendet

**Comment by CurlyMoo** [comment]
> Let us get started and based on demand and add functionality as part of development

That's a pretty cryptical answer 😕 

I leaning towards a more agile approach to pilight in which i want to release new functionality much quicker (automatically), but in order to do so, we must follow the guideliness and vision of continues integrations and [extreme programming](https://en.wikipedia.org/wiki/Extreme_programming) tightly.

That means, we don't just add functionality because it works, but because it's properly (unit)tested, documented, integrated, and fits in the general vision on what the software (architecture) should and should not do. If you don't you'll eventually end up in an dead end street, because the whole software is knotted together and stops working properly. And i know what i'm talking about because when i started rewrite, i was confronted with the same issues in pilight development. I never programming in C before when i started pilight and it was the greatest lesson learned in both the good and best practices.

**Pull request closed without merging**
